# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SpeedTestUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


#from PyQt5 import QtCore, QtGui, QtWidgets


#class Ui_gif(object):
#    def setupUi(self, gif):
#        gif.setObjectName("gif")
#        gif.resize(1174, 649)
##        self.centralwidget = QtWidgets.QWidget(gif)
#        self.centralwidget.setObjectName("centralwidget")
#        self.label = QtWidgets.QLabel(self.centralwidget)
#        self.label.setGeometry(QtCore.QRect(0, -10, 1181, 671))
#        self.label.setText("")
#        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\keshav\\Desktop\\NidaAI\\DataBase\\Gui\\speedTest.gif"))
#        self.label.setScaledContents(True)
#        self.label.setObjectName("label")
#        gif.setCentralWidget(self.centralwidget)

#        self.retranslateUi(gif)
#        QtCore.QMetaObject.connectSlotsByName(gif)

#    def retranslateUi(self, gif):
#        _translate = QtCore.QCoreApplication.translate
#        gif.setWindowTitle(_translate("gif", "MainWindow"))


#if __name__ == "__main__":
 #   import sys
 #   app = QtWidgets.QApplication(sys.argv)
 #   gif = QtWidgets.QMainWindow()
 #   ui = Ui_gif()
 #   ui.setupUi(gif)
 #   gif.show()
 #   sys.exit(app.exec_())

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SpeedTest(object):

    def setupUi(self, SpeedTest):

        SpeedTest.setObjectName("SpeedTest")
        SpeedTest.resize(1174, 649)
        self.centralwidget = QtWidgets.QWidget(SpeedTest)
        self.centralwidget.setObjectName("centralwidget")
        self.gif = QtWidgets.QLabel(self.centralwidget)
        self.gif.setGeometry(QtCore.QRect(0, -10, 1181, 671))
        self.gif.setText("")
        self.gif.setPixmap(QtGui.QPixmap("C:\\Users\\keshav\\Desktop\\NidaAI\\DataBase\\Gui\\speedTest.gif"))
        self.gif.setScaledContents(True)
        self.gif.setObjectName("gif")
        SpeedTest.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpeedTest)
        QtCore.QMetaObject.connectSlotsByName(SpeedTest)

    def retranslateUi(self, SpeedTest):
        _translate = QtCore.QCoreApplication.translate
        SpeedTest.setWindowTitle(_translate("SpeedTest", "MainWindow"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpeedTest = QtWidgets.QMainWindow()
    ui = Ui_SpeedTest()
    ui.setupUi(SpeedTest)
    SpeedTest.show()
    sys.exit(app.exec_())
